name: "SonarQube Pull Request Comment"
description: >
  Check if a project / analysis passed the Quality Gate check
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  sonar_host_url:
    description: "SonarQube Url"
    required: true
  sonar_token:
    description: "Token Project Sonar"
    required: true
  sonar_projectkey:
    description: "Name Project"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
outputs:
  quality_check:
    description: >
      The resulting Status SonarQube 
runs:
  using: "composite"
  steps:
    - name: Set execute permission for the script
      shell: bash
      run: chmod +x $GITHUB_ACTION_PATH/script/project-status.sh
      
    - name: Checking Sonar
      id: check
      shell: bash
      run: $GITHUB_ACTION_PATH/script/project-status.sh
        # echo "quality_check=$(<quality_check)" >> $GITHUB_ENV
      env: 
       SONAR_HOST_URL: ${{ inputs.sonar_host_url }}
       SONAR_TOKEN: ${{ inputs.sonar_token }}
       SONAR_PROJECTKEY: ${{ inputs.sonar_projectkey }}
      # Save the output to a file to read it later


    - name: PR Comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.quality_check
          })
