name: "SonarQube PR Comment Action"
description: "Checks SonarQube Quality Gate status and comments on a pull request."
inputs:
  sonar_host_url:
    description: "SonarQube URL"
    required: true
  sonar_token:
    description: "SonarQube authentication token"
    required: true
  sonar_projectkey:
    description: "SonarQube project key"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  repo_name: 
    description: "Repository name"
    required: true
  pr_number:
    description: "Pull Request number"
    required: true
outputs:
  quality_check:
    description: "Quality check status from SonarQube"
runs:
  using: "docker"
  image: "Dockerfile"